### ISSUE TITLE
Add a "permission-resolvable" alias

### ISSUE THREAD

**Issue by TohruMKDM** [SovietKitsune/discordia-types#3]
This would be the type for the methods `Permissions:disable(...)`, `Permissions:enable(...)`, `PermissionOverwrite:allowPermissions(...)`, `PermissionOverwrite:clearPermissions(...)`, `PermissionOverwrite:denyPermissions(...)`
It should look like this 
![image](https://user-images.githubusercontent.com/100388505/186072889-8b46b093-2015-43a7-9f62-f59ff7f4c162.png)

**Comment by Sylviettee** [comment]
Fixed by 59cd28b678dd672d827577b6050a4a7eebbf8604
